# Generated by Django 4.2.3 on 2023-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_coupon_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
