# Generated by Django 4.2.3 on 2023-08-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_coupon_minimum_purchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='max_discount_amount',
            new_name='min_or_max_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_purchase_amount',
        ),
    ]
