# Generated by Django 4.2.3 on 2023-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_rename_max_discount_amount_coupon_min_or_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
