# Generated by Django 4.2.2 on 2023-07-12 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bookvariant_slug_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariant',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='variant_cover_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
