# Generated by Django 4.2.2 on 2023-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bookvariant_image_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariant',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
    ]
