# Generated by Django 4.2.2 on 2023-07-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_bookvariant_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_image',
            new_name='VariantImages',
        ),
    ]
