# Generated by Django 4.2.3 on 2023-08-07 05:02

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_offer_percentage_bookvariant_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=image_cropping.fields.ImageCropField(upload_to='book_covers/'),
        ),
    ]
