# Generated by Django 4.2.3 on 2023-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='covertype',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
