# Generated by Django 4.2.3 on 2023-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_covertype_slug_language_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertype',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
