# Generated by Django 4.2.3 on 2023-08-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_covertype_slug_alter_language_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariant',
            name='offer_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
