# Generated by Django 4.2.2 on 2023-07-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_address_mobile_alter_address_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street_address',
        ),
    ]
