# Generated by Django 4.2.3 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND', 'refund'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], default='PENDING', max_length=20),
        ),
    ]
