# Generated by Django 4.2.3 on 2023-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('PROCESSING', 'Processing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT FAILED', 'Payment failed'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('COD', 'Cash on Delivery')], default='PENDING', max_length=20),
        ),
    ]
